### PR TITLE
speedOrb that increases fireRate by 3x, added to Item Manager

### PR DESCRIPTION
**Pull request by b24nguyen**

### CODE REVIEW

**Comment by mpitropov** [comment]
The code looks good and the orb refactoring is nice.
I think there might be some issues with the sprite changing, a sort of race condition.

Lets say the player gets power orb and then 10 seconds later gets speed orb.
The first issue would be that the player has two powers but their sprite would be speed mode.
The second issue is that after another 10 seconds the 20 second timeout on the power mode will be run and the user will be turned to a regular sprite even though they have 10 seconds left of speed mode.

**Comment by b24nguyen** [comment]
I think I know what you're talking about after looking at it. Didn't consider returning invoked disable would change the player model back to playerReg while you still have powerups. I guess we need to a major refactor so we can view work with both statuses at the same time? 

Not sure how to proceed

**Comment by eatorres** [comment]
Should I make different sprite colors for the power-ups?

**Comment by b24nguyen** [comment]
Nah the issue is that we invoke a disableXMode method 10 seconds into the future. So if you pick up a powerOrb, you'll be orange and then you pick up a speedOrb before disablePowerMode is called. Then when you hit 10s for the powerOrb, diablePowerMode will be called and turn the player back to original sprite even though you should be blue from the speedOrb

**Comment by b24nguyen** [comment]
I think we need to refactor PlayerControl and PlayerHealthManager so we have PlayerController + PlayerModel. PlayerModel keeps track of your statuses and your hp numbers. PlayerController handles all of the player logic

**Comment by mpitropov** [comment]
LGTM

**Pull request merged**
